### ISSUE TITLE
Issue with robomongo download

### ISSUE THREAD

**Issue by robmsmt** [gatblau/europa#2]
It appears the link is broken for robomongo which causes the download to fail (404 error) which means that the install fails.

Although it appears in the comments that this link was updated recently; by following the install instructions it did not use the latest .app URL.

--2015-12-17 23:15:39--  http://robomongo.org/files/linux/robomongo-0.8.5-x86_64.rpm
Resolving robomongo.org (robomongo.org)... 
Connecting to robomongo.org (robomongo.org) connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-17 23:15:39 ERROR 404: Not Found.

Replacing the failed file with a manually downloaded one is a suitable workaround.

**Comment by gatblau** [comment]
Take a look at the readme file under "Building the development version" section. It explains how to build the very latest code (in case the fix is not tagged). This should fix your problem if the fix was added after the latest tag. For information, it is likely that download links will change over time. So, you could simply fix the issues by updating the download URI for the broken link in the fetch.sh file.
